# envs/dev/sample-nginx.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-sample-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saraoncloud95/newspulse-argocd.git
    targetRevision: HEAD
    path: manifests/sample-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
